### PR TITLE
Update api_main.css

### PR DESCRIPTION
**Pull request by 1Jesper1**
Fix for long urls

### CODE REVIEW

**Comment by 1Jesper1** [comment]
@kevinmuller Would you like to take a look?

**Comment by stripthis** [comment]
Hi Jesper,

We cannot merge this pull request. 
The css files are compiled from less files, you need to modify these and compile.
Check the grunt tasks for this.

**Comment by 1Jesper1** [comment]
Thanks for the reply!

**Comment by 1Jesper1** [comment]
I have compiled the css from less files. Could you check if my fix does solve the problem?

**Comment by stripthis** [comment]
Sure will do, if that makes sense we'll include it in the next release.

**Comment by stripthis** [comment]
Hi @1Jesper1, 

Sorry for the wait. I just had a look and I don't understand what you want to achieve with your change as I do not see any difference in terms of results in the styleguide. Do you want to wrap the urls on two lines? Currently they are truncated with an ellipsis. Like:

screen shot 2018-06-06 at 12 23 05

Can you explain / show what you are trying to do?

**Comment by 1Jesper1** [comment]
bug
bug fix

First one is without the word-wrap, the last image is with the word-wrap added.
@stripthis

**Comment by stripthis** [comment]
@1Jesper1 which browser / os are you using? Seems like the elipsis is not supported.

**Comment by 1Jesper1** [comment]
@stripthis 
Browser: Chrome Version 67.0.3396.62 (Official build) (64x)
OS: Windows 10 64x

**Comment by stripthis** [comment]
Ok so the issue is not in the styleguide but in the application itself. It's missing a wrapper div to the ellispis. Closing this issue as we'll fix it with the app and not the styleguide. Thanks!

screen shot 2018-06-06 at 13 39 36

**Comment by 1Jesper1** [comment]
Good to hear you found the fix! @stripthis

**Comment by stripthis** [comment]
Fixed with v2.1

**Pull request closed without merging**
